import {safeLink} from './safeLink';
import React,{useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,CalendarDays,MailCheck,RefreshCw} from 'lucide-react';
import * as P from './progressModel';
import {StatusBadge} from './Progress';
import './campaign.css';
type Row=Record<string,any>;
type Props={api:(path:string,method?:string,data?:any)=>Promise<any>,openJob:(job:Row)=>void};
const stages=['DISCOVERED','SHORTLISTED','PREPARING','APPLIED','RECRUITER_CONTACT','SCREENING','ASSESSMENT','INTERVIEW','FINAL_INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN','NO_RESPONSE','ARCHIVED'];
const label=(s:string)=>(s||'').replaceAll('_',' ');
const date=(s:string)=>s?new Date(s).toLocaleDateString(undefined,{day:'numeric',month:'short'}):'Not recorded';
function useCampaign(api:Props['api']){const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');const load=()=>api('/campaign').then(value=>{setData(value);setError('')}).catch(e=>setError(e.message));useEffect(()=>{load();const timer=setInterval(load,30000);window.addEventListener('campaign-updated',load);return()=>{clearInterval(timer);window.removeEventListener('campaign-updated',load)}},[]);return {data,error,load};}
/** #47: a verified read (canonical follow-ups, review queue size, pipeline or the latest scan's telemetry). */
function useVerified(api:Props['api'],path:string){const [data,setData]=useState<Row|null>(null),[failed,setFailed]=useState(false);const load=()=>api(path).then(value=>{setData(value);setFailed(false)}).catch(()=>setFailed(true));useEffect(()=>{load();window.addEventListener('campaign-updated',load);return()=>window.removeEventListener('campaign-updated',load)},[path]);return {data,failed,load};}

export function Campaign({api,openJob,page,goTo}:{page:string,goTo:(page:string)=>void}&Props){
 if(page==='Applications')return <Pipeline api={api} openJob={openJob}/>;
 return <Today api={api} openJob={openJob} goTo={goTo}/>;
}

function Today({api,openJob,goTo}:Props&{goTo:(page:string)=>void}){
 const {data,error,load}=useCampaign(api);const verified=useVerified(api,'/progress?period=this_week'),scan=useVerified(api,'/search/telemetry');const [tab,setTab]=useState('Today');
 if(!data)return <section className="panel" role="status">{error||'Loading your search…'}{error&&<button className="secondary" onClick={load}>Retry</button>}</section>;
 const c=data.campaign,v=verified.data,review=v?.review?.total,followups=v?.actions?.followups,actions=v?.actions?.next_actions,head=P.runHeadline(scan.failed?null:scan.data),latest=scan.data?.run;
 const opportunities=(jobs:Row[])=>jobs.length?jobs.map(j=><button className="campaign-job" key={j.id} onClick={()=>openJob(j)}><div><strong>{j.title}</strong><span>{j.company} · {j.location}</span></div><span className="fit-band">Priority {j.match_score}<ArrowUpRight size={16} aria-hidden/></span></button>):<p className="campaign-empty">Nothing here yet. Review Discovery or add a job you found on a UAE portal.</p>;
 const due=(item:Row)=><span className={item.overdue?'due-date':''}>{item.overdue?'Overdue · ':item.due_now?'Today · ':''}{P.formatDay(item.due_on)}</span>;
 const newCount=latest?.telemetry?.funnel?` · ${latest.telemetry.counts_complete?'':'at least '}${latest.telemetry.funnel.NEW} new relevant`:'';
 return <div className="campaign">{error&&<p role="alert">{error}</p>}
 <div className="campaign-heading"><div><span className="eyebrow">{c.name}</span><h2>Your next moves</h2><p>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} · Dubai, Abu Dhabi and the wider UAE</p></div></div>
 {typeof review==='number'&&review>0&&<div className="next-action today-review"><MailCheck size={20} aria-hidden/><p><strong>{P.plural(review,'Gmail message')}</strong> {review===1?'needs':'need'} your decision before {review===1?'it counts':'they count'} as an application.</p><button className="primary compact" onClick={()=>goTo('Progress')}>Review in Progress<ArrowRight size={16} aria-hidden/></button></div>}
 <div className="campaign-tabs" role="tablist">{['Today','Search elsewhere','Campaign preferences'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Today'&&<><div className="campaign-foot scan-line"><span>Last scan{latest?.run_created_at?' '+P.formatDateTime(latest.run_created_at):''}: <StatusBadge tone={head.tone}>{head.label}</StatusBadge> {head.detail}{newCount}</span>{(data.discovery_health?.not_checked||[]).length?<span>Not checked: {data.discovery_health.not_checked.map((s:Row)=>`${s.name} (${String(s.reason).toLowerCase().replace('_',' ')})`).join(', ')}</span>:null}</div><div className="today-grid"><section className="panel"><div className="sectiontitle"><h2>Highest-ranked new jobs</h2><span>{data.strong_new.length}</span></div><p className="campaign-note">Ordered by ASTRA’s heuristic priority index. A ranking is a suggestion to review, not a validated match.</p>{opportunities(data.strong_new)}</section><section className="panel next-actions"><h2>Follow-ups & next actions</h2>{verified.failed&&<p className="campaign-empty" role="alert">Follow-ups could not load. <button className="textbtn" onClick={verified.load}>Retry</button></p>}{v&&!followups?.items?.length&&!actions?.items?.length&&<p className="campaign-empty">No follow-ups or next actions in the next seven days.</p>}{followups?.items?.map((r:Row)=><button className="campaign-job" key={'f'+r.application_id} onClick={()=>openJob({id:r.job_id})}><div><strong>{r.company}</strong><span>Follow up · {r.title}</span></div>{due(r)}</button>)}{actions?.items?.map((r:Row)=><button className="campaign-job" key={'a'+r.application_id} onClick={()=>openJob({id:r.job_id})}><div><strong>{r.action}</strong><span>{r.company} · {r.title}</span></div>{due(r)}</button>)}{followups?.date_not_recorded>0&&<p className="campaign-note">{P.plural(followups.date_not_recorded,'follow-up')} without a valid date {followups.date_not_recorded===1?'is':'are'} not listed.</p>}<h3>Upcoming interviews & assessments</h3>{data.upcoming.length?data.upcoming.map((r:Row)=><div className="campaign-job" key={r.id}><CalendarDays size={18} aria-hidden/><div><strong>{r.company}</strong><span>{r.stage} · {date(r.date)}</span></div></div>):<p className="campaign-empty">Add a meeting or assessment when you receive one.</p>}</section></div>
 <section className="panel spaced"><div className="sectiontitle"><h2>Saved, ready for your review</h2><span>{data.saved.length}</span></div>{opportunities(data.saved)}</section><PortalPack api={api} compact/>
 <div className="campaign-foot"><button className="textbtn" onClick={()=>goTo('Progress')}>See verified progress<ArrowRight size={15} aria-hidden/></button><span>{data.excel.error|| (data.excel.revision>data.excel.exported_revision?'Excel update pending':'Excel updated '+date(data.excel.last_success))}</span></div></>}
 {tab==='Search elsewhere'&&<PortalPack api={api}/>}{tab==='Campaign preferences'&&<><Preferences api={api} cfg={c} reload={load}/><Reliability api={api}/></>}
 </div>
}

/** Applications: canonical current state per application (#46), not the legacy stage. */
function Pipeline({api,openJob}:Props){
 const {data,failed,load}=useVerified(api,'/progress/applications');const [filter,setFilter]=useState('');
 if(!data)return <section className="panel" role="status">{failed?<>Applications could not load. <button className="secondary" onClick={load}>Retry</button></>:'Loading applications…'}</section>;
 const items:Row[]=data.items||[];const counts:Record<string,number>={};items.forEach(r=>{counts[r.current_state]=(counts[r.current_state]||0)+1});
 const shown=items.filter(r=>!filter||r.current_state===filter);const submitted=items.filter(r=>r.submitted).length;
 return <div className="campaign pipeline"><div className="toolbar"><label>Filter by current stage<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All stages ({items.length})</option>{P.STATES.map(s=><option key={s} value={s}>{P.stateLabel(s)} ({counts[s]||0})</option>)}</select></label><span>{P.plural(data.total,'tracked application')} · {submitted} submitted{data.truncated?` · showing the ${items.length} most recently changed`:''}</span></div>
 <p className="campaign-note">Stages come from each application’s recorded history. Where an older field disagrees, it is shown as the legacy stage and is not used.</p>
 <section className="panel">{shown.length?shown.map((r:Row)=><button className="campaign-job" key={r.application_id} onClick={()=>openJob({id:r.job_id})}><div><strong>{r.title}</strong><span>{r.company} · {r.submitted?(r.submitted_at?'Submitted '+P.formatDay(r.submitted_at):'Submitted, date not recorded'):'Not submitted'}</span><span>CV: {r.cv_version||'Not recorded'}{r.followup_due_on?' · Follow up '+P.formatDay(r.followup_due_on):''}{r.legacy_stage?' · Legacy stage: '+label(r.legacy_stage).toLowerCase():''}</span></div><span className="fit-band">{P.stateLabel(r.current_state)}<ArrowUpRight size={16} aria-hidden/></span></button>):<p className="campaign-empty">{items.length?'No application is at this stage.':'No applications are tracked yet. Track a job from its detail view.'}</p>}</section></div>
}

function Preferences({api,cfg,reload}:{api:Props['api'],cfg:Row,reload:()=>void}){
 const [value,setValue]=useState(cfg),[message,setMessage]=useState('');
 return <form className="panel" onSubmit={async e=>{e.preventDefault();try{await api('/campaign/settings','PUT',value);setMessage('Campaign preferences saved');reload()}catch(e:any){setMessage(e.message)}}}><h2>Your search campaign</h2><div className="formgrid">{Object.entries(value).map(([key,v])=><label key={key}>{label(key)}{Array.isArray(v)?<textarea value={v.join('\n')} onChange={e=>setValue({...value,[key]:e.target.value.split('\n').filter(Boolean)})}/>:<input type={typeof v==='number'?'number':key.includes('date')?'date':'text'} value={v} onChange={e=>setValue({...value,[key]:typeof v==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div><p>Primary target roles and excluded titles remain editable in Settings. Adjacent roles and target country affect discovery; primary cities affect sorting. Other campaign preferences record your plan and do not yet enforce eligibility filters. Your CV is never sent to portals to generate searches.</p><button className="primary">Save campaign</button><p role="status">{message}</p></form>
}

export function PortalPack({api,compact=false}:{api:Props['api'],compact?:boolean}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');
 const load=()=>api('/campaign/portals').then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 if(!data)return <section className="panel spaced">{error||'Loading UAE search destinations…'}</section>;
 const sources=compact?data.daily:data.sources;
 return <section className="panel spaced"><div className="sectiontitle"><div><h2>{compact?'Today’s UAE search pack':'Search elsewhere'}</h2><p>Open a source in your browser. Import worthwhile jobs using Add job.</p></div><button className="icon" aria-label="Refresh search pack" onClick={load}><RefreshCw size={17}/></button></div><div className="portal-list">{sources.map((s:Row)=><div className="portal-row" key={s.id}><div><strong>{s.name}</strong><small>{s.details.group} · {s.cadence} · Next check {date(s.next_check)} · {s.query} · {s.details.last_checked?'Checked '+date(s.details.last_checked):'Not checked yet'}</small></div>{!compact&&<select aria-label={'Check cadence for '+s.name} value={s.cadence} onChange={async e=>{try{await api('/campaign/portals/'+s.id,'PUT',{cadence:e.target.value,watching:true});load()}catch(e:any){setError(e.message)}}}>{['DAILY','ROTATING','WEEKLY'].map(c=><option key={c}>{c}</option>)}</select>}<a className="secondary" href={safeLink(s.url)} target="_blank" rel="noreferrer">Open <ArrowUpRight size={14}/></a><button className="icon" aria-label={'Mark '+s.name+' checked'} title="Mark checked after your review" onClick={async()=>{try{await api('/campaign/portals/'+s.id+'/checked','POST',{});load()}catch(e:any){setError(e.message)}}}><Check size={18}/></button></div>)}</div>{error&&<p role="alert">{error}</p>}</section>
}

function PreferredSource({api,job}:{api:Props['api'],job:Row}){
 const [url,setUrl]=useState(job.analysis?.preferred_application_url||''),[message,setMessage]=useState('');
 return <details className="spaced"><summary>Application source</summary><p>Discovered via {job.analysis?.discovered_via||job.source}. Save an official employer listing here if you have verified it.</p><label>Preferred application link<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button className="secondary" onClick={async()=>{try{await api('/recall/jobs/'+job.id+'/source','PUT',{preferred_application_url:url});setMessage('Preferred link saved locally.')}catch(e:any){setMessage(e.message)}}}>Save preferred link</button>{job.analysis?.preferred_application_url&&<a className="secondary" href={safeLink(job.analysis.preferred_application_url)} target="_blank" rel="noreferrer">Open preferred listing</a>}<p role="status">{message}</p></details>
}

export function TrackPanel({api,job,onSaved}:{api:Props['api'],job:Row,onSaved:()=>void}){
 const [form,setForm]=useState<Row>({stage:job.application?.tracking?.stage||job.application?.status||'SHORTLISTED',date:new Date().toISOString().slice(0,10),cv_version:job.application?.tracking?.cv_version||'',notes:'',followup_date:'',next_action:job.application?.tracking?.next_action||'',next_action_date:job.application?.tracking?.next_action_date||'',event_type:'',meeting_date:'',meeting_url:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel spaced"><h3>Track this opportunity</h3><PreferredSource api={api} job={job}/>{job.application?.applied_date&&<p>Already applied on {date(job.application.applied_date)}. Update the existing record below.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/campaign/jobs/'+job.id+'/track','POST',form);setMessage('Saved locally. Excel will update automatically.');window.dispatchEvent(new Event('campaign-updated'));onSaved()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}><div className="formgrid"><label>Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Event date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>CV version used<input list="cv-versions" placeholder="e.g. General focus — September" value={form.cv_version} onChange={e=>setForm({...form,cv_version:e.target.value})}/><datalist id="cv-versions"><option>Master CV</option><option>General focus</option><option>Not recorded</option>{job.resumes?.map((r:Row)=><option key={r.id}>{'CV #'+r.id}</option>)}</datalist></label><label>Record a reply or note<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}><option value="">Stage update only</option><option value="MEANINGFUL_RESPONSE">Genuine employer / recruiter reply</option><option value="AUTOMATED_CONFIRMATION">Automated receipt</option><option value="NOTE">Personal note</option><option value="FOLLOWUP_COMPLETED">Follow-up completed</option></select></label><label>Follow-up date<input type="date" value={form.followup_date} onChange={e=>setForm({...form,followup_date:e.target.value})}/></label><label>Next action<input value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><label>Next action date<input type="date" value={form.next_action_date} onChange={e=>setForm({...form,next_action_date:e.target.value})}/></label></div><label>Meeting or assessment date (Dubai time)<input type="datetime-local" value={form.meeting_date} onChange={e=>setForm({...form,meeting_date:e.target.value})}/></label><label>Meeting link (optional)<input type="url" value={form.meeting_url} onChange={e=>setForm({...form,meeting_url:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" disabled={busy}>{form.stage==='APPLIED'?'Mark as applied':'Save tracking update'}</button><p role="status">{message}</p></form></section>
}

export function Reliability({api}:{api:Props['api']}){
 const [state,setState]=useState<Row>({}),[message,setMessage]=useState('');
 useEffect(()=>{api('/campaign/windows-schedule').then(setState).catch(e=>setMessage(e.message))},[]);
 const disable=async()=>{try{setState(await api('/campaign/windows-schedule','POST',{action:'Disable',hours:6}));setMessage('Legacy Windows discovery task disabled')}catch(e:any){setMessage(e.message)}};
 return <section className="panel spaced"><h2>Scanning and backups</h2><p>ASTRA scans only when you press Start Scan in Discovery and confirm. It never scans in the background, on a timer, or when Windows or the app starts, and it no longer installs or starts a Windows scheduled task.</p><p>Legacy Windows task: {state.installed?(state.enabled?'Present and enabled — it now runs a no-op':'Present, disabled'):'Not installed'}</p><div className="actions">{state.installed&&state.enabled&&<button className="secondary" onClick={disable}>Disable legacy task</button>}<button className="secondary" onClick={async()=>{try{await api('/campaign/backup','POST',{});setMessage('Local backup saved')}catch(e:any){setMessage(e.message)}}}>Back up now</button></div><p role="status">{message}</p></section>
}
