import React,{useEffect,useState} from 'react';
import {ArrowUpRight,Check,CalendarDays,Target,RefreshCw} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from 'recharts';
import './campaign.css';
type Row=Record<string,any>;
type Props={api:(path:string,method?:string,data?:any)=>Promise<any>,openJob:(job:Row)=>void};
const stages=['DISCOVERED','SHORTLISTED','PREPARING','APPLIED','RECRUITER_CONTACT','SCREENING','ASSESSMENT','INTERVIEW','FINAL_INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN','NO_RESPONSE','ARCHIVED'];
const label=(s:string)=>(s||'').replaceAll('_',' ');
const date=(s:string)=>s?new Date(s).toLocaleDateString(undefined,{day:'numeric',month:'short'}):'Not recorded';
const pct=(v:any)=>v===null||v===undefined?'Not enough data':Math.round(v*100)+'%';
function useCampaign(api:Props['api']){const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');const load=()=>api('/campaign').then(value=>{setData(value);setError('')}).catch(e=>setError(e.message));useEffect(()=>{load();const timer=setInterval(load,30000);window.addEventListener('campaign-updated',load);return()=>{clearInterval(timer);window.removeEventListener('campaign-updated',load)}},[]);return {data,error,load};}

export function Campaign({api,openJob,page}:{page:string}&Props){
 const {data,error,load}=useCampaign(api);const [tab,setTab]=useState('Today'),[filter,setFilter]=useState('');
 if(!data)return <section className="panel" role="status">{error||'Loading your search…'}{error&&<button className="secondary" onClick={load}>Retry</button>}</section>;
 const m=data.metrics,c=data.campaign;
 const opportunities=(jobs:Row[])=>jobs.length?jobs.map(j=><button className="campaign-job" key={j.id} onClick={()=>openJob(j)}><div><strong>{j.title}</strong><span>{j.company} · {j.location}</span></div><span className="fit-band">{j.fit_band?label(j.fit_band)+' FIT':'Review'}<ArrowUpRight size={16}/></span></button>):<p className="campaign-empty">Nothing here yet. Review Discovery or add a job you found on a UAE portal.</p>;
 return <div className="campaign">{error&&<p role="alert">{error}</p>}
 {page==='Today'&&<><div className="campaign-heading"><div><span className="eyebrow">{c.name}</span><h2>Your next moves</h2><p>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})} · Dubai, Abu Dhabi and the wider UAE</p></div><div className="weekly-goal"><Target size={20}/><div><strong>{m.quality_this_week} / {c.weekly_target}</strong><span>quality applications this week</span><small>{m.this_week} total submitted · historical fit may be unrecorded</small></div></div></div>
 <div className="campaign-tabs" role="tablist">{['Today','Search elsewhere','Campaign preferences'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Today'&&<><p className="campaign-foot">Last discovery: {data.discovery_health?.last?new Date(data.discovery_health.last).toLocaleString():'Not run'} · {data.discovery_health?.new||0} new · {data.discovery_health?.healthy||0}/{data.discovery_health?.attempted||0} sources healthy{data.discovery_health?.errors?' · Discovery needs attention':''}</p><div className="today-grid"><section className="panel"><div className="sectiontitle"><h2>Strong new matches</h2><span>{data.strong_new.length}</span></div>{opportunities(data.strong_new)}</section><section className="panel next-actions"><h2>Follow-ups & next actions</h2>{!data.followups.length&&<p className="campaign-empty">No follow-ups due this week.</p>}{data.followups.map((r:Row)=><button className="campaign-job" key={r.id} onClick={()=>openJob(r.job)}><div><strong>{r.job.company}</strong><span>{r.job.title}</span></div><span className={new Date(r.followup.due_date)<new Date()?'due-date':''}>{date(r.followup.due_date)}</span></button>)}{data.next_actions?.map((r:Row)=><button className="campaign-job" key={'action'+r.id} onClick={()=>openJob(r.job)}><div><strong>{r.tracking.next_action}</strong><span>{r.job.company} · {date(r.tracking.next_action_date)}</span></div></button>)}<h3>Upcoming interviews & assessments</h3>{data.upcoming.length?data.upcoming.map((r:Row)=><div className="campaign-job" key={r.id}><CalendarDays size={18}/><div><strong>{r.company}</strong><span>{r.stage} · {date(r.date)}</span></div></div>):<p className="campaign-empty">Add a meeting or assessment when you receive one.</p>}</section></div>
 <section className="panel spaced"><div className="sectiontitle"><h2>Saved, ready for your review</h2><span>{data.saved.length}</span></div>{opportunities(data.saved)}</section><PortalPack api={api} compact/>
 <div className="campaign-foot"><span>{m.total} submitted · {m.active} active · {m.interviews} reached interview</span><span>{data.excel.error|| (data.excel.revision>data.excel.exported_revision?'Excel update pending':'Excel updated '+date(data.excel.last_success))}</span></div></>}
 {tab==='Search elsewhere'&&<PortalPack api={api}/>}{tab==='Campaign preferences'&&<><Preferences api={api} cfg={c} reload={load}/><Reliability api={api}/></>}
 </>}
 {page==='Progress'&&<><div className="campaign-kpis">{[['This week',m.this_week],['This month',m.this_month],['Submitted',m.total],['Active',m.active],['Responses',m.responses],['Interviews',m.interviews],['Offers',m.offers]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><section className="panel spaced"><h2>Outcomes, with the right context</h2><div className="outcome-rates"><div><strong>{pct(m.response_rate)}</strong><span>Mature response rate · n={m.mature_count}</span></div><div><strong>{pct(m.interview_rate)}</strong><span>Application → interview · n={m.total}</span></div><div><strong>{pct(m.offer_rate)}</strong><span>Application → offer · n={m.total}</span></div></div><p>Response rate counts genuine employer replies for applications at least {m.observation_days} days old. Automated receipts do not count. Interview and offer rates count each submitted application once.</p><p>{m.response_sample?`Median first response: ${m.median_response_days.toFixed(1)} days, from ${m.response_sample} responses.`:'No meaningful response dates recorded yet.'} Small samples describe your activity; they do not prove one approach is better.</p></section><section className="panel spaced"><h2>Applications by week</h2>{m.weeks.length?<ResponsiveContainer width="100%" height={220}><BarChart data={m.weeks}><XAxis dataKey="week"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="applications" fill="#82dcb8" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<p>Not enough data yet.</p>}</section>
 <div className="review-grid">{Object.entries(m.groups).map(([group,rows])=><section className="panel" key={group}><h2>{({source:'Sources',emirate:'Emirates',role:'Role families',cv:'CV versions',fit:'Fit at application'} as Row)[group]}</h2><div className="tablewrap"><table><thead><tr><th>{group}</th><th>Applied</th><th>Replies</th><th>Interviews</th><th>Offers</th></tr></thead><tbody>{(rows as Row[]).map(r=><tr key={r.name}><td>{r.name}</td><td>{r.applications}</td><td>{r.responses}</td><td>{r.interviews}</td><td>{r.offers}</td></tr>)}</tbody></table>{!(rows as Row[]).length&&<p>Not enough data yet.</p>}</div></section>)}</div><section className="panel spaced"><h2>Last seven days</h2><div className="campaign-kpis">{Object.entries(data.weekly_review||{}).map(([name,count])=><div key={name}><span>{label(name).toLowerCase()}</span><strong>{String(count)}</strong></div>)}</div><h2>30-day review</h2><p>Compare the source, emirate, role, CV and fit tables above after your observation window. Keep exploring when samples are small. Historical fit and CV versions remain “Not recorded” until you supply them.</p><p>Discovery holds {data.coverage.relevant_jobs} potentially relevant jobs from {data.coverage.relevant_employers} employers. {data.coverage.fresh_24h} have a posting date within 24 hours; {data.coverage.old_postings_90d} were posted over 90 days ago and need a fresh availability check. {data.coverage.posting_date_unknown} have no verified posting date. Fetched vacancy counts do not measure market coverage.</p>{data.coverage.top_two_employer_share>=.8&&<p className="notice">Coverage concentration: {pct(data.coverage.top_two_employer_share)} of potentially relevant jobs come from two employers. Use your manual search pack to broaden coverage.</p>}</section></>}
 {page==='Applications'&&<><div className="toolbar"><label>Filter your pipeline<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All stages</option>{stages.map(s=><option key={s}>{s}</option>)}</select></label><span>{data.applications.length} tracked · {m.total} submitted</span></div><section className="panel">{data.applications.filter((r:Row)=>!filter||r.stage===filter).map((r:Row)=><button className="campaign-job" key={r.id} onClick={()=>openJob(r.job)}><div><strong>{r.job.title}</strong><span>{r.job.company} · {r.emirate} · Applied {date(r.applied_date)}</span><span>CV: {r.tracking.cv_version||'Not recorded'}{r.followup&&!r.followup.done?' · Follow up '+date(r.followup.due_date):''}</span></div><span className="fit-band">{label(r.stage)}<ArrowUpRight size={16}/></span></button>)}</section></>}
 </div>
}

function Preferences({api,cfg,reload}:{api:Props['api'],cfg:Row,reload:()=>void}){
 const [value,setValue]=useState(cfg),[message,setMessage]=useState('');
 return <form className="panel" onSubmit={async e=>{e.preventDefault();try{await api('/campaign/settings','PUT',value);setMessage('Campaign preferences saved');reload()}catch(e:any){setMessage(e.message)}}}><h2>Your search campaign</h2><div className="formgrid">{Object.entries(value).map(([key,v])=><label key={key}>{label(key)}{Array.isArray(v)?<textarea value={v.join('\n')} onChange={e=>setValue({...value,[key]:e.target.value.split('\n').filter(Boolean)})}/>:<input type={typeof v==='number'?'number':key.includes('date')?'date':'text'} value={v} onChange={e=>setValue({...value,[key]:typeof v==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div><p>Primary target roles and excluded titles remain editable in Settings. Adjacent roles and target country affect discovery; primary cities affect sorting. Other campaign preferences record your plan and do not yet enforce eligibility filters. Your CV is never sent to portals to generate searches.</p><button className="primary">Save campaign</button><p role="status">{message}</p></form>
}

export function PortalPack({api,compact=false}:{api:Props['api'],compact?:boolean}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');
 const load=()=>api('/campaign/portals').then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 if(!data)return <section className="panel spaced">{error||'Loading UAE search destinations…'}</section>;
 const sources=compact?data.daily:data.sources;
 return <section className="panel spaced"><div className="sectiontitle"><div><h2>{compact?'Today’s UAE search pack':'Search elsewhere'}</h2><p>Open a source in your browser. Import worthwhile jobs using Add job.</p></div><button className="icon" aria-label="Refresh search pack" onClick={load}><RefreshCw size={17}/></button></div><div className="portal-list">{sources.map((s:Row)=><div className="portal-row" key={s.id}><div><strong>{s.name}</strong><small>{s.details.group} · {s.cadence} · Next check {date(s.next_check)} · {s.query} · {s.details.last_checked?'Checked '+date(s.details.last_checked):'Not checked yet'}</small></div>{!compact&&<select aria-label={'Check cadence for '+s.name} value={s.cadence} onChange={async e=>{try{await api('/campaign/portals/'+s.id,'PUT',{cadence:e.target.value,watching:true});load()}catch(e:any){setError(e.message)}}}>{['DAILY','ROTATING','WEEKLY'].map(c=><option key={c}>{c}</option>)}</select>}<a className="secondary" href={s.url} target="_blank" rel="noreferrer">Open <ArrowUpRight size={14}/></a><button className="icon" aria-label={'Mark '+s.name+' checked'} title="Mark checked after your review" onClick={async()=>{try{await api('/campaign/portals/'+s.id+'/checked','POST',{});load()}catch(e:any){setError(e.message)}}}><Check size={18}/></button></div>)}</div>{error&&<p role="alert">{error}</p>}</section>
}

function PreferredSource({api,job}:{api:Props['api'],job:Row}){
 const [url,setUrl]=useState(job.analysis?.preferred_application_url||''),[message,setMessage]=useState('');
 return <details className="spaced"><summary>Application source</summary><p>Discovered via {job.analysis?.discovered_via||job.source}. Save an official employer listing here if you have verified it.</p><label>Preferred application link<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button className="secondary" onClick={async()=>{try{await api('/recall/jobs/'+job.id+'/source','PUT',{preferred_application_url:url});setMessage('Preferred link saved locally.')}catch(e:any){setMessage(e.message)}}}>Save preferred link</button>{job.analysis?.preferred_application_url&&<a className="secondary" href={job.analysis.preferred_application_url} target="_blank" rel="noreferrer">Open preferred listing</a>}<p role="status">{message}</p></details>
}

export function TrackPanel({api,job,onSaved}:{api:Props['api'],job:Row,onSaved:()=>void}){
 const [form,setForm]=useState<Row>({stage:job.application?.tracking?.stage||job.application?.status||'SHORTLISTED',date:new Date().toISOString().slice(0,10),cv_version:job.application?.tracking?.cv_version||'',notes:'',followup_date:'',next_action:job.application?.tracking?.next_action||'',next_action_date:job.application?.tracking?.next_action_date||'',event_type:'',meeting_date:'',meeting_url:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel spaced"><h3>Track this opportunity</h3><PreferredSource api={api} job={job}/>{job.application?.applied_date&&<p>Already applied on {date(job.application.applied_date)}. Update the existing record below.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/campaign/jobs/'+job.id+'/track','POST',form);setMessage('Saved locally. Excel will update automatically.');window.dispatchEvent(new Event('campaign-updated'));onSaved()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}><div className="formgrid"><label>Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Event date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>CV version used<input list="cv-versions" placeholder="e.g. General focus — September" value={form.cv_version} onChange={e=>setForm({...form,cv_version:e.target.value})}/><datalist id="cv-versions"><option>Master CV</option><option>General focus</option><option>Not recorded</option>{job.resumes?.map((r:Row)=><option key={r.id}>{'CV #'+r.id}</option>)}</datalist></label><label>Record a reply or note<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}><option value="">Stage update only</option><option value="MEANINGFUL_RESPONSE">Genuine employer / recruiter reply</option><option value="AUTOMATED_CONFIRMATION">Automated receipt</option><option value="NOTE">Personal note</option><option value="FOLLOWUP_COMPLETED">Follow-up completed</option></select></label><label>Follow-up date<input type="date" value={form.followup_date} onChange={e=>setForm({...form,followup_date:e.target.value})}/></label><label>Next action<input value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><label>Next action date<input type="date" value={form.next_action_date} onChange={e=>setForm({...form,next_action_date:e.target.value})}/></label></div><label>Meeting or assessment date (Dubai time)<input type="datetime-local" value={form.meeting_date} onChange={e=>setForm({...form,meeting_date:e.target.value})}/></label><label>Meeting link (optional)<input type="url" value={form.meeting_url} onChange={e=>setForm({...form,meeting_url:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" disabled={busy}>{form.stage==='APPLIED'?'Mark as applied':'Save tracking update'}</button><p role="status">{message}</p></form></section>
}

export function Reliability({api}:{api:Props['api']}){
 const [state,setState]=useState<Row>({}),[hours,setHours]=useState(6),[message,setMessage]=useState('');
 useEffect(()=>{api('/campaign/windows-schedule').then(setState).catch(e=>setMessage(e.message))},[]);
 const change=async(action:string)=>{try{if(action==='RunNow'){await api('/search/scan','POST',{});setMessage('Discovery requested. Follow its progress in Discovery.');return}const result=await api('/campaign/windows-schedule','POST',{action,hours});setState(result);setMessage(action==='Enable'?'Windows background discovery enabled':action==='RunNow'?'Scheduled run requested':action==='Remove'?'Scheduled task removed':'Windows background discovery disabled')}catch(e:any){setMessage(e.message)}};
 return <section className="panel spaced"><h2>Keep your search running</h2><p>The app checks public employer feeds while its server runs. You can also enable a visible Windows Scheduled Task to check while the app is closed. Your computer must be awake and you must be signed in. It will not wake your computer.</p><p>Windows task: {state.installed?(state.enabled?'Enabled':'Installed, disabled'):'Not installed'} · {state.Frequency||'No Windows schedule'} · Last result: {state.LastTaskResult??'Not run'}{state.LastRunTime?' · Last run '+String(state.LastRunTime):''}{state.NextRunTime?' · Next run '+String(state.NextRunTime):''}</p><div className="actions"><label>Check interval<select value={hours} onChange={e=>setHours(Number(e.target.value))}>{[3,6,12,24].map(h=><option value={h} key={h}>{h} hours</option>)}</select></label><button className="primary" onClick={()=>change('Enable')}>Enable background discovery</button><button className="secondary" onClick={()=>change('Disable')}>Disable</button><button className="secondary" disabled={!state.installed} onClick={()=>change('Remove')}>Remove task</button><button className="secondary" onClick={()=>change('RunNow')}>Run now</button><button className="secondary" onClick={async()=>{try{await api('/campaign/backup','POST',{});setMessage('Local backup saved')}catch(e:any){setMessage(e.message)}}}>Back up now</button></div><p role="status">{message}</p></section>
}
