import React,{useEffect,useState} from 'react';
type Row=Record<string,any>;
type Api=(path:string,method?:string,data?:any)=>Promise<any>;
export function PrivacyPanel({api,refresh}:{api:Api,refresh:()=>Promise<any>}){
 const [info,setInfo]=useState<Row|null>(null),[profile,setProfile]=useState<Row>({}),[candidate,setCandidate]=useState<Row|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[scope,setScope]=useState('cv'),[confirmation,setConfirmation]=useState(''),[key,setKey]=useState('');
 const [checks,setChecks]=useState<Row|null>(null),[events,setEvents]=useState<Row[]>([]),[usage,setUsage]=useState<Row|null>(null);
 const securityCheck=async()=>{const [c,e,u]=await Promise.all([api('/privacy/self-check'),api('/privacy/security-events'),api('/privacy/ai-usage')]);setChecks(c);setEvents(e.events);setUsage(u)};
 const load=async()=>{const [data,person]=await Promise.all([api('/privacy'),api('/profile')]);setInfo(data);setProfile(data.application_profile);setCandidate(person)};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const run=async(fn:()=>Promise<any>,success:string)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();setMessage(success)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const edit=(name:string,value:any)=>setProfile({...profile,[name]:value});
 const text=(name:string,label:string)=> <label key={name}>{label}<input dir="auto" value={profile[name]||''} maxLength={1000} onChange={e=>edit(name,e.target.value)}/></label>;
 const choices=(name:string,label:string,options:string[])=> <label key={name}>{label}<select value={profile[name]||'UNKNOWN'} onChange={e=>edit(name,e.target.value)}>{options.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label>;
 const expected:Record<string,string>={cv:'DELETE CV',history:'DELETE APPLICATION HISTORY',all:'DELETE ALL LOCAL DATA'};
 async function exportData(){const token=sessionStorage.getItem('token');const response=await fetch('/api/privacy/export',{headers:token?{Authorization:'Bearer '+token}:{}});if(!response.ok){const data=await response.json();throw Error(data.detail||'Export failed')}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='job-search-private-export.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 return <div className="privacy-panel" aria-busy={busy}>
  {error&&<div role="alert" className="errorbar">{error}<button onClick={()=>run(load,'Loaded')} disabled={busy}>Retry</button></div>}
  {message&&<p role="status" className="notice">{message}</p>}
  {!info&&!error&&<p role="status">Loading local data controlsâ€¦</p>}
  {info&&<>
   <section className="panel spaced"><h2>Privacy & security check</h2><p>Local server, credential storage, runtime, data permissions and backups.</p><button className="secondary" disabled={busy} onClick={()=>run(securityCheck,'Security check finished')}>Run security check</button>
    {checks&&<><h3>{checks.overall}</h3>{checks.checks.map((c:Row)=><p key={c.check}><strong>{c.check.replaceAll('_',' ')}: {c.status}</strong> — {c.detail}{c.remediation&&<> · {c.remediation}</>}</p>)}</>}
    {usage&&<><h3>Optional OpenAI usage today (UTC)</h3><p>{usage.requests} requests · {usage.input_tokens} input tokens · {usage.output_tokens} output tokens. Failed attempts count toward the limit. Local Ollama is excluded.</p><label>Daily AI request limit (0 turns off remote requests)<input type="number" min={0} max={100} value={usage.daily_limit} onChange={e=>setUsage({...usage,daily_limit:Number(e.target.value)})}/></label><button disabled={busy} onClick={()=>run(async()=>{await api('/settings','PUT',{ai_daily_limit:usage.daily_limit});await securityCheck()},'Daily AI limit saved')}>Save daily AI limit</button></>}
    {!!events.length&&<><h3>Recent security events</h3>{events.slice(-10).reverse().map((e:Row,i:number)=><p key={i}>{e.ts} · {e.event.replaceAll('_',' ').toLowerCase()}</p>)}</>}
   </section>
   <section className="panel"><h2>Privacy & local data</h2><p>Stored on this computer: <code dir="ltr">{info.storage_path}</code></p>{Object.entries(info.copy).map(([name,value])=><p key={name}>{String(value)}</p>)}<button className="secondary" disabled={busy} onClick={()=>run(exportData,'Private export downloaded. It contains unencrypted personal information.')}>Export My Data</button></section>
   <section className="panel spaced"><h2>Application profile</h2><p>These are your own answers, separate from extracted CV text. Blank fields mean unknown. They never become demographic matching variables or automatically submitted answers.</p>
    <form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/privacy/application-profile','PUT',profile);localStorage.setItem('uiLocale',profile.ui_locale);localStorage.setItem('uiTimeZone',profile.timezone);document.documentElement.dir=/^(ar|he|fa|ur)(-|$)/i.test(profile.ui_locale)?'rtl':'ltr';document.documentElement.lang='en';await refresh()},'Application profile saved locally. Interface text is currently English; locale controls formatting and direction.')}}>
     <div className="formgrid">
      {text('preferred_name','Preferred name')}{text('legal_name','Legal name (only if needed)')}{text('residence_country','Residence country code (for example AE)')}
      <label>Target employment country codes<input dir="ltr" value={(profile.target_countries||[]).join(', ')} onChange={e=>edit('target_countries',e.target.value.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean))}/></label>
      {text('ui_locale','Formatting locale (for example en-GB, ar-AE, de-DE)')}{text('cv_language','CV language â€” separate from interface locale')}{text('timezone','Timezone (for example Europe/Berlin)')}
      {choices('relocation','Willing to relocate',['UNKNOWN','YES','NO'])}{choices('travel','Willing to travel',['UNKNOWN','YES','NO'])}{text('notice_period','Notice period')}
      <label>Languages you explicitly provide<input dir="auto" value={(profile.languages||[]).join(', ')} onChange={e=>edit('languages',e.target.value.split(',').map(s=>s.trim()).filter(Boolean))}/></label>
      {text('salary_amount','Salary preference (your notation)')}{text('salary_currency','Salary currency code, for example EUR')}{choices('salary_period','Salary period',['UNKNOWN','hour','day','week','month','year'])}
      {text('portfolio','Portfolio HTTPS link')}{text('github','GitHub HTTPS link')}{text('linkedin','LinkedIn HTTPS link')}
     </div>
     <fieldset><legend>Preferred work arrangement</legend>{['remote','hybrid','on-site'].map(mode=><label className="check" key={mode}><input type="checkbox" checked={(profile.work_modes||[]).includes(mode)} onChange={e=>edit('work_modes',e.target.checked?[...(profile.work_modes||[]),mode]:profile.work_modes.filter((m:string)=>m!==mode))}/>{mode}</label>)}</fieldset>
     {(profile.target_countries||[]).map((country:string)=><fieldset key={country}><legend>{country}: answers apply only to this country</legend><div className="formgrid">{[['work_authorisation','Authorised to work'],['sponsorship','Require sponsorship']].map(([name,label])=><label key={name}>{label}<select value={profile[name]?.[country]||'UNKNOWN'} onChange={e=>edit(name,{...profile[name],[country]:e.target.value})}>{['UNKNOWN','YES','NO'].map(v=><option key={v}>{v}</option>)}</select></label>)}</div><p>Local CV and legal guidance has not been verified for this market. Follow the employerâ€™s instructions; no sensitive details or photograph are added automatically.</p></fieldset>)}
     <button className="primary" disabled={busy}>Save application profile</button>
    </form>
   </section>
   {candidate&&<section className="panel spaced"><h2>Career facts and provenance</h2><p>{candidate.confirmed?'VERIFIED by your confirmation':'EXTRACTED â€” NEEDS CONFIRMATION'}. Review each source block. A correction is recorded as user-provided and requires reconfirmation before generating documents.</p>{['skills','employments','education','certifications','projects'].map(kind=><div key={kind}><h3>{kind}</h3>{(candidate[kind]||[]).map((fact:Row)=><form key={fact.id} onSubmit={e=>{e.preventDefault();run(async()=>{await api('/profile/facts/'+kind+'/'+fact.id,'PUT',{text:fact.text});await load();await refresh()},'Source fact corrected. Review and confirm the profile again before generating documents.')}}><label>Source fact #{fact.id}<textarea dir="auto" value={fact.text} maxLength={20000} onChange={e=>setCandidate({...candidate,[kind]:candidate[kind].map((f:Row)=>f.id===fact.id?{...f,text:e.target.value}:f)})}/></label><small>{fact.provenance}</small><button className="secondary" disabled={busy}>Save corrected fact</button></form>)}</div>)}<button className="primary" disabled={busy} onClick={()=>run(async()=>{await api('/profile','PUT',{confirmed:true});await load();await refresh()},'Career facts confirmed by you.')}>I reviewed and confirm these career facts</button></section>}
   <section className="panel spaced"><h2>Optional cloud advice</h2><p>Rules mode needs no key. Saving a key does not authorise transmission: each OpenAI advice request asks separately. The key is stored in your operating systemâ€™s credential manager, never in the app database.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/privacy/credentials/openai','PUT',{key});setKey('')},'API key saved in the native credential store. No cloud request was made.')}}><label>OpenAI API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} minLength={10} maxLength={1000} required/></label><button className="secondary" disabled={busy}>Save key securely</button></form></section>
   <section className="panel spaced"><h2>Platform capabilities</h2>{info.platforms.map((p:Row)=><p key={p.platform}><strong>{p.platform}</strong>: {p.discovery.toLowerCase()}; application submission is manual. {p.source.startsWith('https:')&&<a href={p.source} target="_blank" rel="noreferrer">Integration reference</a>}</p>)}</section>
   <section className="panel spaced"><h2>Delete local data</h2><p>This cannot be undone. Export first if you need a copy. CV deletion also removes generated materials, approved answers, the application profile, notes, app tracker copies and backups. Application-history deletion retains the master CV and candidate profile but removes application records, documents, notes, tracker copies and backups. All-data deletion also removes saved jobs and sources and pauses scanning. Original files and exports outside the app remain.</p>
    <form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/privacy/delete','POST',{scope,confirmation});setConfirmation('');await load();await refresh()},'Selected app-managed data was deleted. Copies outside this app remain under your control.')}}>
     <label>What to delete<select value={scope} onChange={e=>{setScope(e.target.value);setConfirmation('')}}><option value="cv">Delete CV and derived private material</option><option value="history">Delete Application History</option><option value="all">Delete All Local Data</option></select></label>
     <label>Type {expected[scope]}<input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>
     <button className="secondary" disabled={busy||confirmation!==expected[scope]}>Delete selected local data</button>
    </form>
   </section>
  </>}
 </div>
}
