import React,{useEffect,useState} from 'react';
type Row=Record<string,any>;
export function Recall({api,openJob}:{api:(path:string,method?:string,data?:any)=>Promise<any>,openJob:(j:Row)=>void}){
 const [data,setData]=useState<Row|null>(null),[tab,setTab]=useState('recommendations'),[error,setError]=useState(''),[reason,setReason]=useState(''),[quality,setQuality]=useState('');
 const load=()=>api('/recall').then(setData).catch(e=>setError(e.message));
 useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[]);
 if(!data)return <section className="panel spaced">{error||'Loading discovery evidence…'}</section>;
 const counts=data.latest?.report?.funnel?.counts;
 const rows=data[tab]||[];
 const decide=async(id:number,decision:string)=>{try{await api('/recall/jobs/'+id+'/feedback','POST',{decision,reason,quality_label:quality});load()}catch(e:any){setError(e.message)}};
 return <><section className="panel spaced"><div className="sectiontitle"><h2>Opportunities to review</h2><label>Search policy <select aria-label="Search policy" value={data.policy} onChange={async e=>{try{await api('/recall/policy','PUT',{policy:e.target.value});load()}catch(e:any){setError(e.message)}}}>{['STRICT','BALANCED','EXPLORATORY'].map(p=><option key={p}>{p}</option>)}</select></label></div><p>Balanced keeps plausible experience gaps for review. Explicit restrictions stay separate. Scores are priorities, not hiring probabilities.</p><div className="viewtabs">{[['recommendations','Recommended'],['near_misses','Near misses'],['adjacent','Adjacent opportunities']].map(([key,label])=><button className={key===tab?'primary':'secondary'} key={key} onClick={()=>setTab(key)}>{label} ({data[key].length})</button>)}</div><label>Optional feedback reason <select aria-label="Feedback reason" value={reason} onChange={e=>setReason(e.target.value)}>{['','too senior','wrong field','wrong location','nationality restriction','salary','company','other'].map(r=><option key={r} value={r}>{r||'No reason selected'}</option>)}</select></label><details><summary>Optional search-quality label</summary><label>For the next feedback action<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="">Not labelled</option><option value="FALSE_POSITIVE">Bad recommendation</option><option value="FALSE_NEGATIVE">Good job missed by discovery</option></select></label></details>{error&&<p role="alert">{error}</p>}
 {rows.length?rows.map((j:Row)=><article className="opportunity" key={j.id}><div><button className="textbtn jobname" onClick={()=>openJob(j)}>{j.title}</button><small>{j.company} · {j.location}</small><strong>{j.decision.fit_band} FIT · {j.decision.priority}/100</strong><small>{j.decision.freshness.replaceAll('_',' ')} · {j.analysis?.seen_at?'Previously opened':'New to you'} · Posted {j.date_posted?new Date(j.date_posted).toLocaleDateString():'date unknown'}</small>{j.decision.soft.map((r:Row)=><small key={r.code}>{r.evidence}</small>)}{tab==='near_misses'&&<p>{j.decision.why_review}</p>}</div><div className="actions"><button className="secondary" onClick={()=>decide(j.id,'INTERESTED')}>Interested</button><button className="secondary" onClick={()=>decide(j.id,'NOT_FOR_ME')}>Not for me</button></div></article>):<p className="campaign-empty">No opportunities in this group. Use Search elsewhere to check sources outside the automatic feeds.</p>}</section>
 {counts&&<details className="panel spaced"><summary>Latest scan evidence · {counts.fetched} fetched, {counts.plausible} plausible, {counts.new} new</summary><h3>Successive filtering steps</h3>{Object.entries(data.latest.report.funnel.stages||{}).map(([key,value])=><p key={key}>{key}: {String(value)}</p>)}<h3>All scan attributes</h3><p>These attributes overlap. Hard exclusions have one primary reason each.</p><div className="tablewrap"><table><tbody>{Object.entries(counts).map(([key,value])=><tr key={key}><th>{key.replaceAll('_',' ')}</th><td>{String(value)}</td></tr>)}</tbody></table></div><h3>Primary exclusion reasons</h3>{Object.entries(data.latest.report.funnel.primary_exclusions).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {String(value)}</p>)}<p>Started {new Date(data.latest.created_at).toLocaleString()} · {data.latest.report.trigger} · {data.latest.report.duration_seconds}s</p></details>}
 <details className="panel spaced"><summary>Source contribution & seven-day observation</summary><div className="tablewrap"><table><thead><tr><th>Source</th><th>Health</th><th>Fetched</th><th>UAE</th><th>Plausible</th><th>Reviewed</th><th>Applied</th></tr></thead><tbody>{data.scorecards.map((s:Row)=><tr key={s.id}><td>{s.name}</td><td>{s.enabled?s.health:'PAUSED'}</td><td>{s.last_result.scanned??'—'}</td><td>{s.last_result.funnel?.counts.uae??'—'}</td><td>{s.last_result.funnel?.counts.plausible??'—'}</td><td>{s.reviewed}</td><td>{s.applications}</td></tr>)}</tbody></table></div><p>{data.observation.length} job records in the last seven days. Feedback stays local; rejection outcomes do not change relevance rules.</p><button className="secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exported_at:new Date().toISOString(),policy:data.policy,observations:data.observation},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='discovery-seven-day-observation.json';a.click();URL.revokeObjectURL(url)}}>Export observation notes</button>{data.potential_employers.map((r:Row)=><p key={r.company}>Potential watchlist employer: {r.company} ({r.manual_jobs} manual discoveries). Review its official careers site before adding a feed.</p>)}</details></>
}

export function PasteJob({api,onFields}:{api:(p:string,m?:string,d?:any)=>Promise<any>,onFields:(v:Row)=>void}){
 const [text,setText]=useState(''),[message,setMessage]=useState('');
 return <details><summary>Paste job details to fill this form</summary><label>Copied job text<textarea value={text} onChange={e=>setText(e.target.value)} placeholder={'Job title: Graduate Analyst\nCompany: Example\nLocation: Dubai\nPaste the description below'}/></label><button type="button" className="secondary" onClick={async()=>{try{const r=await api('/recall/paste-preview','POST',{text});onFields(r.fields);setMessage('Fields filled locally. Review them before saving. No website was loaded.')}catch(e:any){setMessage(e.message)}}}>Fill fields for review</button><p role="status">{message}</p></details>
}
