import {Recall} from './Recall';
import React,{useEffect,useState} from 'react';
import {formatDateTime,timeZone} from './locale';
import {compareJobs} from './jobOrder';
type Row=Record<string,any>;
type Props={api:(path:string,method?:string,data?:any)=>Promise<any>;openJob:(j:Row)=>void;refresh:()=>Promise<any>};
const when=(value:string)=>value?formatDateTime(value):'Not scanned yet';
export function ScanProgress({activeScan,cancellable,stopSaving,onStop}:{activeScan:Row;cancellable:boolean;stopSaving:boolean;onStop:()=>void}){
 const progress=activeScan.progress||{};
 const retryStop=Boolean(activeScan.cancel_requested_at&&activeScan.stop_durable===false);
 return <section className="panel spaced" aria-live="polite"><div className="sectiontitle"><h2>Scan in progress</h2><span className="pill">{retryStop?'STOP NEEDS RETRY':activeScan.cancel_requested_at?'STOPPING':'RUNNING'}</span></div><progress aria-label="Scan progress" max={progress.sources_total||1} value={progress.sources_done||0}/><p>{progress.sources_done||0} of {progress.sources_total||0} sources done{progress.current_source?' · Now checking '+progress.current_source:''} · {progress.postings_seen||0} postings checked</p>{(progress.scope_changed_sources||[]).length>0&&<p className="notice">Not checked, because they changed after you confirmed: {progress.scope_changed_sources.map((s:Row)=>`${s.name} (${String(s.change).toLowerCase()})`).join(', ')}.</p>}{retryStop?<><p className="notice">Stop is taking effect, but the app could not confirm it was saved. Retry saving Stop before closing the app. The source being checked now may finish first.</p><button className="secondary" disabled={stopSaving} onClick={onStop}>{stopSaving?'Saving Stop…':'Retry saving Stop'}</button></>:activeScan.cancel_requested_at?<p className="notice">Stopping. No further sources will be fetched; the source being checked now finishes first.</p>:<button className="secondary" disabled={!cancellable||stopSaving} onClick={onStop}>{stopSaving?'Saving Stop…':'Stop scan'}</button>}</section>
}
export function Discovery({api,openJob,refresh}:Props){
 const [data,setData]=useState<Row>({sources:[],runs:[]}),[jobs,setJobs]=useState<Row[]>([]),[cfg,setCfg]=useState<Row>({}),[error,setError]=useState(''),[pending,setPending]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState('');
 const [scanState,setScanState]=useState<Row>({}),[preview,setPreview]=useState<Row|null>(null),[starting,setStarting]=useState(false),[stopSaving,setStopSaving]=useState(false);
 const [view,setView]=useState(localStorage.getItem('discoveryView')||'active'),[query,setQuery]=useState(''),[days,setDays]=useState('0'),[source,setSource]=useState(''),[sort,setSort]=useState('uae_first');
 async function load(){const [d,j,c,s]=await Promise.all([api('/search/overview'),api('/jobs'),api('/settings'),api('/scan/status')]);setData(d);setJobs(j);setCfg(c);setScanState(s)}
 // Manual-only scanning: Start Scan only opens a preview of the scope and
 // workload. Nothing is fetched until the Owner confirms, and the confirmation
 // token is single-use, so one confirmation starts at most one scan.
 async function openPreview(sourceId?:number){setError('');try{setPreview(await api('/scan/preview','POST',sourceId?{source_id:sourceId}:{}))}catch(e:any){setError(e.message)}}
 async function confirmScan(){if(!preview||starting)return;setStarting(true);setError('');try{await api('/scan/start','POST',{token:preview.token});await load()}catch(e:any){setError(e.message)}finally{setPreview(null);setStarting(false)}}
 async function stopScan(){const run=scanState.active;if(!run||stopSaving)return;setStopSaving(true);setError('');try{await api('/scan/cancel','POST',{run_id:run.id})}catch(e:any){setError(e.message)}finally{try{await load()}catch(e:any){setError(e.message)}setStopSaving(false)}}
 useEffect(()=>{let alive=true;const poll=()=>{if(alive)load().catch(e=>setError(e.message))};poll();const timer=setInterval(poll,5000);return()=>{alive=false;clearInterval(timer)}},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[data.runs[0]?.id,data.runs[0]?.status]);
 async function act(fn:()=>Promise<any>){setPending(true);setError('');try{await fn();await load();await refresh()}catch(e:any){setError(e.message)}finally{setPending(false)}}
 const active=(j:Row)=>!['SKIP','APPLIED','RECRUITER_CONTACT','SCREENING','ASSESSMENT','INTERVIEW','FINAL_INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN','NO_RESPONSE','ARCHIVED'].includes(j.status);
 const fresh=(j:Row)=>Date.now()-Date.parse(j.date_found)<7*86400000;
 const filtered=jobs.filter(j=>(view==='all'||view==='saved'&&j.analysis?.saved||view==='active'&&active(j)||view==='new'&&active(j)&&fresh(j)||view==='skipped'&&j.status==='SKIP')&&(!source||j.analysis?.discovery?.source_id===Number(source))&&(!Number(days)||Date.now()-Date.parse(j.date_found)<Number(days)*86400000)&&(j.title+' '+j.company+' '+j.location).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>compareJobs(a,b,sort,cfg.campaign?.primary_emirates||[]));
 const latest=data.runs.find((r:Row)=>r.status!=='RUNNING');
 const activeScan=scanState.active;
 const running=pending||starting||data.running||!!activeScan;
 const duration=(s?:number|null)=>s==null?'Unknown — no finished scan on this device yet':s<60?'Under a minute':`About ${Math.round(s/60)} minute${Math.round(s/60)===1?'':'s'}`;
 return <><div className="discoveryhero panel"><div><div className="eyebrow">YOUR DAILY JOB SEARCH</div><h2>Scan. Shortlist. Follow through.</h2><p>Public company boards, filtered for your roles and locations. New matches are scored automatically.</p><small>Scans run only when you press Start Scan. Nothing scans when Windows or ASTRA starts, on a timer, or after a restart. · {timeZone()}</small>{scanState.last?.status==='INTERRUPTED'&&<small className="notice">Your last scan was interrupted when the app stopped. It was not restarted.</small>}{(scanState.last?.scope_changed_sources||[]).length>0&&<small className="notice">Your last scan did not check {scanState.last.scope_changed_sources.map((s:Row)=>`${s.name} (${String(s.change).toLowerCase()} after you confirmed)`).join(', ')}.</small>}</div><button className="primary startscan" disabled={running||!!preview} onClick={()=>openPreview()}>{activeScan?'Scan in progress…':'Start Scan'}</button></div>
 {preview&&!activeScan&&<section className="panel spaced" role="dialog" aria-label="Review scan before starting"><h2>Review this scan before it starts</h2><p>{preview.scope.single_source?'One source':'Every enabled source'} will be checked once. Nothing is fetched until you confirm.</p><ul>{preview.scope.sources.map((s:Row)=><li key={s.id}><strong>{s.name}</strong> · {s.adapter} · {s.postings_last_seen!=null?`${s.postings_last_seen} postings last time`:'no earlier scan'}</li>)}</ul><p>Roles: {preview.scope.career_tracks.join(', ')||'your saved focus'} ({preview.scope.target_roles} role titles) · Locations: {preview.scope.locations.join(', ')||'not set'}</p><p>Expected workload: {preview.workload.sources} source{preview.workload.sources===1?'':'s'} · {preview.workload.postings_last_seen!=null?`about ${preview.workload.postings_last_seen} postings`:'posting count unknown'} · {duration(preview.workload.estimated_seconds)}</p><small>{preview.workload.requests}</small><div className="actions spaced"><button className="primary" disabled={starting} onClick={confirmScan}>{starting?'Starting…':'Confirm and start scan'}</button><button className="secondary" disabled={starting} onClick={()=>setPreview(null)}>Cancel</button></div></section>}
 {activeScan&&<ScanProgress activeScan={activeScan} cancellable={!!scanState.cancellable} stopSaving={stopSaving} onStop={stopScan}/>}
 {error&&<p role="alert" className="notice">{error}</p>}
 <div className="metrics spaced">{[['Open shortlist',jobs.filter(active).length],['New in 7 days',jobs.filter(j=>active(j)&&fresh(j)).length],['Enabled sources',data.sources.filter((s:Row)=>s.enabled).length],['Sources needing attention',data.sources.filter((s:Row)=>s.enabled&&s.result?.error).length]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <Recall api={api} openJob={openJob}/><details className="spaced"><summary>All stored jobs and bookmarks</summary> <section className="panel"><div className="sectiontitle"><h2>Your shortlist</h2><small>{filtered.length} opportunities</small></div><div className="viewtabs">{[['active','Open shortlist'],['new','New this week'],['saved','Saved'],['skipped','Skipped'],['all','All saved']].map(([v,label])=><button className={view===v?'primary':'secondary'} key={v} onClick={()=>{setView(v);localStorage.setItem('discoveryView',v)}}>{label}</button>)}</div><div className="toolbar spaced"><input aria-label="Search discoveries" placeholder="Search role, company or location" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Discovery source filter" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{data.sources.map((s:Row)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Discovery sort order" value={sort} onChange={e=>setSort(e.target.value)}><option value="uae_first">UAE first · score · newest</option><option value="match_score">Highest score · newest</option><option value="date_found">Newest discovered · score</option></select><select aria-label="Discovery age" value={days} onChange={e=>setDays(e.target.value)}><option value="0">Any discovery date</option><option value="7">Found in last 7 days</option><option value="30">Found in last 30 days</option><option value="90">Found in last 90 days</option></select></div>
 {filtered.length?<div className="discoverylist">{filtered.map(j=><div className="opportunity" key={j.id}><div><button className="textbtn jobname" onClick={()=>openJob(j)}>{j.title}</button><small>{j.company} · {j.location}</small><small>{j.analysis?.fit||j.recommendation.replaceAll('_',' ')} · Found {when(j.date_found)}{j.analysis?.discovery?.last_seen?' · Seen '+when(j.analysis.discovery.last_seen):''}</small></div><button className="secondary" disabled={pending} onClick={()=>act(()=>api('/search/jobs/'+j.id+'/save','POST',{saved:!j.analysis?.saved}))}>{j.analysis?.saved?'Saved ✓':'Save'}</button><span className="score">{j.match_score}/100</span></div>)}</div>:<div className="empty"><h3>No matches in this view</h3><p>{view==='active'||view==='new'?'Scan your sources or add more company boards. The scan breakdown below explains exclusions.':'Try changing the search or date filters.'}</p></div>}
 <small>“Seen” means present during a successful scan; it does not guarantee the vacancy is still open. Review eligibility and the original posting.</small></section>
</details>
 <section className="panel spaced"><div className="sectiontitle"><h2>Scanning is manual</h2><span className="pill">MANUAL ONLY</span></div><p>ASTRA never scans on its own. Each scan starts only when you press Start Scan and confirm the scope. Scans only collect and score public listings; nothing is ever submitted.</p></section>
 <section className="panel spaced"><h2>Company sources</h2><p>Add a public Greenhouse, Lever, Ashby or SmartRecruiters board. SmartRecruiters scans UAE listings only. Paste its link; the app handles the connection details.</p><form className="toolbar spaced" onSubmit={e=>{e.preventDefault();act(async()=>{await api('/search/sources','POST',{name,url});setName('');setUrl('')})}}><input aria-label="Source company name" placeholder="Company name" required value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Company board URL" type="url" placeholder="https://jobs.lever.co/company" required value={url} onChange={e=>setUrl(e.target.value)}/><button className="primary" disabled={pending}>Add source</button></form>
 {data.sources.map((s:Row)=><div className="sourcecard" key={s.id}><div><strong>{s.name}</strong><small>{s.adapter} · {s.enabled?'Enabled':'Paused'} · {when(s.last_scan)}</small><p>{s.result?.error?'Scan failed: '+s.result.error:s.result?`${s.result.scanned} checked · ${s.result.imported} new · ${s.result.duplicates} already saved`:'Ready for its first scan'}</p>{s.result&&Object.keys(s.result.filtered||{}).length>0&&<small>{Object.entries(s.result.filtered).map(([reason,n])=>`${n} ${reason.toLowerCase()}`).join(' · ')}</small>}</div><div className="actions"><button className="secondary" disabled={running||!!preview||!s.enabled} onClick={()=>openPreview(s.id)}>Scan this source</button><button className="secondary" disabled={pending} onClick={()=>act(()=>api('/records/sources','POST',{id:s.id,enabled:!s.enabled}))}>{s.enabled?'Pause':'Enable'}</button></div></div>)}</section>
 <section className="panel"><h2>Recent scans</h2>{latest&&<p className="notice">Last finished scan: {latest.report.scanned||0} checked · {latest.report.discovered||0} new · {latest.report.filtered||0} filtered out · {latest.report.failures||0} source errors.</p>}{data.runs.map((r:Row)=><div className="record" key={r.id}><div><strong>{when(r.created_at)}</strong><small>{r.report.discovered||0} new · {r.report.duplicates||0} already saved · {r.report.filtered||0} filtered out{r.report.error?' · '+r.report.error:''}</small></div><span className="pill">{r.status}</span></div>)}</section></>
}

export function Tracking({api,openJob,refresh}:Props){
 const [rows,setRows]=useState<Row[]>([]),[view,setView]=useState('active'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/search/tracking').then(setRows);
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await load();await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const filtered=rows.filter(r=>(view==='all'||view==='due'&&r.due||view==='active'&&!['REJECTED','WITHDRAWN','OFFER'].includes(r.status))&&(r.job.title+' '+r.job.company).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.due)-Number(a.due));
 return <><div className="toolbar"><button className={view==='active'?'primary':'secondary'} onClick={()=>setView('active')}>Active applications</button><button className={view==='due'?'primary':'secondary'} onClick={()=>setView('due')}>Follow-ups due ({rows.filter(r=>r.due).length})</button><button className={view==='all'?'primary':'secondary'} onClick={()=>setView('all')}>All applications</button><input aria-label="Search applications" placeholder="Search company or role" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<p role="alert" className="notice">{error}</p>}
 {filtered.map(r=><section className="panel spaced" key={r.id}><div className="sectiontitle"><div><button className="textbtn jobname" onClick={()=>openJob(r.job)}>{r.job.title}</button><small>{r.job.company} · {r.job.location} · Application #{r.id}</small><small>{r.applied_date?'Applied '+when(r.applied_date):'Not yet submitted'}</small></div><select aria-label={'Status for '+r.job.company} disabled={busy} value={r.status} onChange={e=>act(()=>api('/jobs/'+r.job_id+'/status','POST',{status:e.target.value}))}>{Array.from(new Set([r.status,...(r.status==='OFFER'?['WITHDRAWN']:['REJECTED','WITHDRAWN'].includes(r.status)?[]:['APPLIED','INTERVIEW','OFFER','REJECTED','WITHDRAWN'])])).map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="trackinggrid"><div><label>Personal notes<textarea aria-label={'Notes for '+r.job.company} defaultValue={r.job.notes} onBlur={e=>{if(e.target.value!==r.job.notes)act(()=>api('/search/jobs/'+r.job_id+'/notes','POST',{notes:e.target.value}))}} placeholder="Contact person, interview preparation, next action…"/></label><small>Notes save when you leave the field.</small></div><div><label>Follow-up date (Dubai)<input aria-label={'Follow-up for '+r.job.company} type="date" disabled={busy} value={r.followup?.due_date?new Date(r.followup.due_date).toLocaleDateString('en-CA',{timeZone:'Asia/Dubai'}):''} onChange={e=>{if(e.target.value)act(()=>api('/search/tracking/'+r.id+'/followup','POST',{due_date:e.target.value+'T09:00:00+04:00',done:false}))}}/></label><div className="actions spaced">{r.followup&&<><span className="pill">{r.followup.done?'DONE':r.due?'DUE NOW':'SCHEDULED'}</span><button className="secondary" disabled={busy} onClick={()=>act(()=>api('/search/tracking/'+r.id+'/followup','POST',{due_date:r.followup.due_date,done:!r.followup.done}))}>{r.followup.done?'Reopen':'Mark done'}</button><button className="secondary" disabled={busy} onClick={()=>act(()=>api('/search/tracking/'+r.id+'/followup','POST',{due_date:new Date(Date.now()+7*86400000).toISOString(),done:false}))}>Snooze 7 days</button></>}</div><small>Reminders stay here in the app. Messages are sent by you.</small></div></div></section>)}{!filtered.length&&<section className="panel empty"><h3>{view==='due'?'You’re up to date':'No applications in this view'}</h3><p>Open a job and update its status to keep your progress here.</p></section>}</>
}

